---
# Source: sausage-store/charts/backend-report/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: sausage-store-backend-report-secret
data:
  db: "bW9uZ29kYjovL3JlcG9ydHM6cmVwb3J0c3Bhc3N3b3JkQG1vbmdvZGI6MjcwMTcvc2F1c2FnZS1zdG9yZQ=="
type: Opaque
---
# Source: sausage-store/charts/backend-report/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sausage-store-backend-report-conf
data:
  port: "8080"
---
# Source: sausage-store/charts/backend/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sausage-store-backend-conf
data:
  postgres_uri: jdbc:postgresql://postgresql:5432/sausage-store
  postgres_user: store
  postgres_password: storepassword
  report_path: /logs/reports
  log_path: /logs
---
# Source: sausage-store/charts/frontend/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sausage-store-frontend-conf
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;
    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;
    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        keepalive_timeout  65;
        server {

          listen       80;

          location / {
              root   /usr/share/nginx/html;
              index  index.html;
              try_files $uri $uri/ /index.html;
          }

            location /api {
              proxy_pass http://sausage-store-backend-service:8080;
          }

          error_page   500 502 503 504  /50x.html;
          location = /50x.html {
              root   /usr/share/nginx/html;
          }
      }

    }
---
# Source: sausage-store/charts/infra/templates/mongodb.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-conf
data:
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: rootpassword
---
# Source: sausage-store/charts/infra/templates/postgresql.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-conf
data:
  POSTGRES_DB: sausage-store
  POSTGRES_USER: store
  POSTGRES_PASSWORD: passwordstore
  PG_DATA: /var/lib/postgresql/data/pgdata
---
# Source: sausage-store/charts/backend/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: sausage-store-backend-service
  labels:
    app: sausage-store-backend-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: sausage-store-backend
---
# Source: sausage-store/charts/frontend/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: sausage-store-frontend-service
  labels:
    app: sausage-store-frontend-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: sausage-store-frontend
---
# Source: sausage-store/charts/infra/templates/mongodb.yaml
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb
  clusterIP: None
---
# Source: sausage-store/charts/infra/templates/postgresql.yaml
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgresql
  clusterIP: None
---
# Source: sausage-store/charts/backend-report/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sausage-store-backend-report
  namespace: default
  labels:
    app.kubernetes.io/name: backend-report
    app.kubernetes.io/instance: "sausage-store"
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: "Helm"
    helm.sh/chart: "backend-report-0.1.0"
    app.kubernetes.io/component: backend-report
    app.kubernetes.io/part-of: sausage-store
spec:
  revisionHistoryLimit: 15
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sausage-store-backend-report
  template:
    metadata:
      labels:
        app: sausage-store-backend-report
    spec:
      containers:
        - name: backend-report
          image: kykito/sausage-backend-report:latest
          imagePullPolicy: Always
          env:
            - name: DB
              valueFrom:
                secretKeyRef:
                  name: sausage-store-backend-report-secret
                  key: db
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: sausage-store-backend-report-conf
                  key: port
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi 
          ports:
            - name: backend-report
              containerPort: 8080
      volumes:
      - name: sausage-store-backend-report-conf
        configMap:
          name: sausage-store-backend-report-conf
          items:
            - key: port
              path: port
---
# Source: sausage-store/charts/backend/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sausage-store-backend
  namespace: default
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: "sausage-store"
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: "Helm"
    helm.sh/chart: "backend-0.1.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: sausage-store
spec:
  revisionHistoryLimit: 15
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 50%
    type: RollingUpdate 
  selector:
    matchLabels:
      app: sausage-store-backend
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app: sausage-store-backend
    spec:
      containers:
        - name: backend
          image: kykito/sausage-backend:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: sausage-store-backend-conf
                  key: postgres_uri
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: sausage-store-backend-conf
                  key: postgres_user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: sausage-store-backend-conf
                  key: postgres_password
            - name: REPORT_PATH
              valueFrom:
                configMapKeyRef:
                  name: sausage-store-backend-conf
                  key: report_path
            - name: LOG_PATH
              valueFrom:
                configMapKeyRef:
                  name: sausage-store-backend-conf
                  key: log_path
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi 
          ports:
            - name: backend
              containerPort: 8080
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 1 
      volumes:
      - name: sausage-store-backend-conf
        configMap:
          name: sausage-store-backend-conf
          items:
            - key: postgres_uri
              path: postgres_uri
            - key: postgres_user
              path: postgres_user
            - key: postgres_password
              path: postgres_password
            - key: report_path
              path: report_path
            - key: log_path
              path: log_path
---
# Source: sausage-store/charts/frontend/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sausage-store-frontend
  namespace: default
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: "sausage-store"
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: "Helm"
    helm.sh/chart: "frontend-0.1.0"
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: sausage-store
spec:
  revisionHistoryLimit: 15
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sausage-store-frontend
  template:
    metadata:
      labels:
        app: sausage-store-frontend
    spec:
      containers:
        - name: frontend
          image: kykito/sausage-frontend:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi 
          ports:
            - name: frontend
              containerPort: 80
          volumeMounts:
          - name: sausage-store-frontend-conf
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
            readOnly: true
      volumes:
        - name: sausage-store-frontend-conf
          configMap:
            name: sausage-store-frontend-conf
            items:
              - key: nginx.conf
                path: nginx.conf
---
# Source: sausage-store/charts/backend-report/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sausage-store-backend-report-hpa
  labels:
    app: sausage-store-backend-report-hpa
spec:
  minReplicas: 1
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sausage-store-backend-report
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 80
          type: Utilization
      type: Resource
    - resource:
        name: memory
        target:
          averageUtilization: 80
          type: Utilization
      type: Resource
---
# Source: sausage-store/charts/infra/templates/mongodb.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  annotations:
    helm.sh/hook-weight: "-5"
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:7.0
        envFrom:
          - configMapRef:
              name: mongodb-conf
        ports:
        - containerPort: 27017
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi 
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
# Source: sausage-store/charts/infra/templates/postgresql.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
spec:
  serviceName: postgresql
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:15
        envFrom:
          - configMapRef:
              name: postgresql-conf
        ports:
        - containerPort: 5432
        resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi 
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgresql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
# Source: sausage-store/charts/frontend/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sausage-store-frontend-ingress
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - front-nikitakudukhov.sem2.students-projects.ru
  rules:
    - host: front-nikitakudukhov.sem2.students-projects.ru
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: sausage-store-frontend-service
              port:
                number: 80
---
# Source: sausage-store/charts/backend/templates/deployment.yaml
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: sausage-store-backend-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: sausage-store-backend
  updatePolicy:
    updateMode: Auto 
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledResources:
      - cpu
      - memory
      controlledValues: RequestsAndLimits
      maxAllowed:
        cpu: 1
        memory: 1Gi
      minAllowed:
        cpu: 0m
        memory: 0Mi
---
# Source: sausage-store/charts/infra/templates/mongodb-init.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-init
  annotations:
    helm.sh/hook: "post-install"
    helm.sh/hook-weight: "5"  
spec:
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
      - name: wait-for-mongodb
        image: busybox:1.35
        command:
        - sh
        - -c
        - |
          until nc -z mongodb 27017; do
            echo "Waiting for MongoDB to be ready..."
            sleep 5
          done
          echo "MongoDB is ready!"
      containers:
      - name: mongodb-init
        image: mongo:7.0
        envFrom:
        - configMapRef:
            name: mongodb-conf
        command:
        - sh
        - -c
        - |
          mongo --host mongodb:27017 \
            -u $MONGO_INITDB_ROOT_USERNAME \
            -p $MONGO_INITDB_ROOT_PASSWORD \
            --authenticationDatabase admin \
            --eval "
              db = db.getSiblingDB('sausage-store');
              
              if (!db.getUser('reports')) {
                db.createUser({
                  user: 'appuser',
                  pwd: 'apppassword',
                  roles: [
                    { role: 'readWrite', db: 'sausage-store' }
                  ]
                });
                print('Application user created successfully');
              } else {
                print('Application user already exists');
              }
              
              db.createCollection('initialized');
              print('Database initialization completed');
            "
