{{- if .Values.mongodb.init.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-init
  annotations:
    helm.sh/hook: "post-install"
    helm.sh/hook-weight: "5"  
spec:
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
      - name: wait-for-mongodb
        image: busybox:1.35
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "50m"
        command:
        - sh
        - -c
        - |
          until nc -z mongodb {{ .Values.mongodb.containerPort }}; do
            echo "Waiting for MongoDB to be ready..."
            sleep 5
          done
          echo "MongoDB is ready!"
      containers:
      - name: mongodb-init
        image: mongo:7.0
        envFrom:
        - configMapRef:
            name: mongodb-conf
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        command:
        - /bin/sh
        - -c
        - |
          mongosh --host mongodb:{{ .Values.mongodb.containerPort }} \
            -u $MONGO_INITDB_ROOT_USERNAME \
            -p $MONGO_INITDB_ROOT_PASSWORD \
            --authenticationDatabase admin \
            --eval "
              db = db.getSiblingDB('{{ .Values.mongodb.init.database | default "sausage-store" }}');
              
              if (!db.getUser('{{ .Values.mongodb.init.appUser | default "reports" }}')) {
                db.createUser({
                  user: '{{ .Values.mongodb.appUser | default "reports" }}',
                  pwd: '{{ .Values.mongodb.appPassword | default "reportspassword" }}',
                  roles: [
                    { role: 'readWrite', db: '{{ .Values.mongodb.init.database | default "sausage-store" }}' }
                  ]
                });
                print('Application user created successfully');
              } else {
                print('Application user already exists');
              }
              
              db.createCollection('initialized');
              print('Database initialization completed');
            "
{{- end }}